import sys
import os


def setCloudflareDns():
    makeBak()
    newDns = open("/etc/resolv.conf", 'w')
    servers = """ # Generated by DNS manager Gitub: @zeroarash
nameserver 1.1.1.1
nameserver 1.0.0.1\n"""
    newDns.write(servers)
    newDns.close()
    print("Dns changed to cloudlflare.")


def setGoogleDns():
    makeBak()
    newDns = open("/etc/resolv.conf", 'w')
    servers = """ # Generated by DNS manager Gitub: @zeroarash
nameserver 8.8.8.8\n"""
    newDns.write(servers)
    newDns.close()
    print("Dns changed to Google.")


def set403Dns():
    makeBak()
    newDns = open("/etc/resolv.conf", 'w')
    servers = """ # Generated by DNS manager Gitub: @zeroarash
nameserver 10.202.10.202
nameserver 10.202.10.102
nameserver 1.1.1.1\n"""
    newDns.write(servers)
    newDns.close()
    print("Dns changed to 403.online.")


def defaultDns():
    orgFile = open('/etc/resolv.conf', 'w')
    bakFile = open('resolv.conf.bak', 'r')
    defaultDns = bakFile.read()
    orgFile.write(defaultDns)
    orgFile.close()
    print("Dns changed to defaults.")


def makeBak():
    bakFile = open('resolv.conf.bak', 'w')
    file = open('/etc/resolv.conf', 'r')
    defaultDns = file.read()
    bakFile.write(defaultDns)
    bakFile.close()


if __name__ == "__main__":
    # check for sudo permission
    if os.geteuid() == 0:
        argv = sys.argv
        if argv[1] == '1':
            setCloudflareDns()
        if argv[1] == '2':
            setGoogleDns()
        if argv[1] == '3':
            set403Dns()
        elif argv[1] == '4':
            defaultDns()
    else:
        print("[!] Please run the script with 'sudo'.\n")
